services:
  - type: web
    name: ai-trading-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python real_ai_backend.py
    envVars:
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false