services:
  - type: web
    name: ai-trading-backend
    env: python
    buildCommand: echo "No build required"
    startCommand: python server.py
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false