# Copy this content to Streamlit Cloud Secrets section
# Go to your app settings → Secrets → Paste this content

ANTHROPIC_API_KEY = "your_claude_api_key_here"
OPENAI_API_KEY = "your_openai_api_key_here" 
OPENROUTER_API_KEY = "your_openrouter_api_key_here"
PERPLEXITY_API_KEY = "your_perplexity_api_key_here"

# Optional: Add these if you have them
SLACK_WEBHOOK_URL = "your_slack_webhook_url_here"
ALPACA_API_KEY = "your_alpaca_api_key_here"
ALPACA_SECRET_KEY = "your_alpaca_secret_key_here"