OPENROUTER_API_KEY = "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"
ANTHROPIC_API_KEY = "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"
PERPLEXITY_API_KEY = "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"

# Add your Alpaca API keys for live portfolio tracking
# ALPACA_API_KEY = "your_alpaca_api_key"
# ALPACA_SECRET_KEY = "your_alpaca_secret_key"