# Streamlit Secrets Configuration
# DO NOT commit this file to GitHub - use Streamlit Cloud secrets instead

# Alpaca Trading API
ALPACA_API_KEY = "your_alpaca_api_key_here"
ALPACA_SECRET_KEY = "your_alpaca_secret_key_here"
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"

# OpenRouter API for multi-AI analysis
OPENROUTER_API_KEY = "your_openrouter_api_key_here"

# Optional: Direct AI API keys
ANTHROPIC_API_KEY = "your_anthropic_api_key_here"
OPENAI_API_KEY = "your_openai_api_key_here"

# Optional: Slack integration
SLACK_WEBHOOK_URL = "your_slack_webhook_url_here"

# Database configuration (if using cloud database)
DATABASE_URL = "sqlite:///./recommendation_memory.db"

# Backend configuration
BACKEND_URL = "http://localhost:8000"